# Generated by Django 4.1.7 on 2023-03-04 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_expiringlink_link_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiringlink',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.image', unique=True),
        ),
    ]
