# Generated by Django 4.1.7 on 2023-03-05 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_expiringlink_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiringlink',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='images.image'),
        ),
    ]
